### ISSUE TITLE
Simulation with no action

### ISSUE THREAD

**Issue by kwh5484** [facebookresearch/phyre#12]
Is there a way to run a simulation without taking any action and get the resulting images, similar to pressing "Simulate" in the demo without taking any action?

**Comment by akhti** [comment]
It's possible, but it's not part of public API. So if you are building an agent for a published tier, it's better to avoid.
```
import phyre
import matplotlib.pyplot as plt
task = phyre.loader.load_compiled_task_dict()['00000:000']
_, _, images = phyre.simulator.magic_ponies(task, phyre.simulator.scene_if.UserInput())
plt.imshow(images[0][::-1])
```

**Comment by kwh5484** [comment]
Great, thanks.
