### ISSUE TITLE
Possible issue with simulate_single()

### ISSUE THREAD

**Issue by pizilber** [facebookresearch/phyre#20]
In action_simulator.py, line 238, the function simulate_single() ends with
`return simulation.simulation_status, simulation.images`
and I think it's should be corrected to
`return simulation.status, simulation.images`
since Simulation has now a status attribute and not simulation_status.

Thanks.

**Comment by lauragustafson** [comment]
Fixed and version bumped to v0.2.1. Thanks for pointing this out!
