### ISSUE TITLE
phyre.initialize_simulator() is too slow

### ISSUE THREAD

**Issue by ndrwmlnk** [facebookresearch/phyre#23]
Hi,

`phyre.initialize_simulator()` takes ~15 sec, no matter how many tasks we need, e.g. one task or all available tasks. 

This is probably due to loading and unpacking of `phyre/data/generated_tasks/tasks.bin.lzma`
[permalink](https://github.com/facebookresearch/phyre/blob/1787b546b37ab838934165fec42e9567fbe1e301/src/python/phyre/loader.py#L151)
```
with lzma.open(path) as stream:
    collection = phyre.simulator.deserialize(task_if.TaskCollection(), stream.read())
``` 
while debugging our solver, this every time delay of ~15 sec becomes annoying. 

Would you consider e.g., unpacking all the tasks for the first time of usage of PHYRE in a local folder, and loading unpacked tasks from the folder for every further execution of PHYRE? `phyre.initialize_simulator()` should take ~1 sec then.

Any other ideas/solutions?

Thanks!

**Comment by lauragustafson** [comment]
I replicated this locally, and `phyre. initialize_simulator` takes ~1 second for me for a single task.

**Comment by ndrwmlnk** [comment]
System: macOS 10.14
PyCharm 2019.3
python=3.6
phyre=2.1

The timing depends on the Run/Debug mode: 8/29 sec.

**Terminal$** _python my_solver.py_
`simulator = phyre.initialize_simulator( ('00000:000',) ,  ball ) done in 8 sec`

**PyCharm Run:** _my_solver.py_
`simulator = phyre.initialize_simulator( ('00000:000',) ,  ball ) done in 8 sec`

**PyCharm Debug:** _my_solver.py_
`simulator = phyre.initialize_simulator( ('00000:000',) ,  ball ) done in 29 sec`

Any ideas on how to get in PyCharm Debug mode 1-sec timing instead of 29 sec?

Thanks!

**Comment by akhti** [comment]
Closing as stale
