### ISSUE TITLE
Installing on Mac via pip limited to platform = macosx_10_0

### ISSUE THREAD

**Issue by kasmith** [facebookresearch/phyre#29]
I tried installing phyre locally on my Mac through pip and ran into some issues, which I believe stem from the fact that pypi servers only have wheels built under the assumption that Macs have `--platform macosx_10_0_universal`, and my computer only has support for 10_4 and above. This would not be a problem on Linux, which has the manylinux support.

Would it be possible to add wheels to pypi with more recent Mac platform support? Thanks!

The relevant output of my `pip install -v phyre` where it is searching the wheels is below:

![image](https://user-images.githubusercontent.com/923839/76862974-3d58b300-6835-11ea-8867-0434394d3715.png)

**Comment by AbhishekPatnaik** [comment]
Did u find a solution to it @kasmith I m facing the same problem.

**Comment by pushkarjajoria** [comment]
Is there a way to install phyre on a virtual environment with p3.6 without using conda?

I tried doing this and I was not able to.

**Terminal Output**
_ERROR: Could not find a version that satisfies the requirement phyre (from versions: none)
ERROR: No matching distribution found for phyre_

**Python Details**
_Python 3.6.8_
_pip 20.2_

**OS**
MacOS 10.14.6

I also tried installing though wheel but got an error.
_ERROR: phyre-0.2.1-cp36-none-macosx_10_0_universal.whl is not a supported wheel on this platform._

Please let me know if there is a workaround.

**Comment by akhti** [comment]
This should be fixed now.
