### ISSUE TITLE
incorrect value/need clarification for sim.initial_featurized_objects[0].Xs and Ys

### ISSUE THREAD

**Issue by gkm2708** [facebookresearch/phyre#32]
Hello,

In the task number 00018:007 and 00020:000 the value of X and Y for goal object (bar) is more than one. While the value in the other tasks seem to be in the range of [0,1]. The same is reflected if I try to draw using this value on a pix map.

May you clarify how to handle this data or provide a more refined location value for the objects.
![Screenshot from 2020-07-06 23-04-26](https://user-images.githubusercontent.com/47331654/86643639-281eb480-bfdd-11ea-9f87-5ad51a356f8d.png)

**Comment by akhti** [comment]
That means that the center of the bar is beyond the visible part of the screen, e.g., the bottom bar in https://player.phyre.ai/#/task/00020:000 has length 1.0 (i.e., the width of the screen) and so its center of mass could be out of the [0, 1] range in some task instances. As the object is static it doesn't change physics.

**Comment by akhti** [comment]
Closing as solved
