### ISSUE TITLE
Cross-template folds never contain template 6 in test or dev template sets (10 folds)

### ISSUE THREAD

**Issue by augustinharter** [facebookresearch/phyre#40]
Hi, 

we have a question about the baseline results for cross template cases (PHYRE paper, Table 1, PHYRE-B, DQN, Cross).

Do we understand correct that in each cross-template fold there are 16 training templates and the remaining 9 templates (dev, test) [(link)](https://github.com/facebookresearch/phyre/blob/920cd2cc2d7ee29c08ae6ebff8f0463c2245d603/src/python/phyre/metrics.py#L71) are used for measuring the auccess?

We found that template 6 was never part of the test templates in the 10 cross-template folds provided in the baseline code ([link to 'fold method'](https://github.com/facebookresearch/phyre/blob/920cd2cc2d7ee29c08ae6ebff8f0463c2245d603/src/python/phyre/metrics.py#L71)), thus, template 6 does not contribute to the final cross-template auccess value. Is this intended or that just happened to be?

**Comment by akhti** [comment]
Hi @augustinharter ,

> Do we understand correct that in each cross-template fold there are 16 training templates and the remaining 9 templates (dev, test) (link) are used for measuring the auccess?

Table 1 represent final results. For final results we trained on `train+dev` with hyperparameters obtained from preliminary experiments and tested on `test`. For preliminary experiments we trained all models on `train` and evaluated on `dev`.

>We found that template 6 was never part of the test templates in the 10 cross-template folds provided in the baseline code (link to 'fold method'), thus, template 6 does not contribute to the final cross-template auccess value. Is this intended or that just happened to be?

That's a very interesting observation! It was not planned to be so, we use random allocation and apparently some tasks got luckier than others.
