### ISSUE TITLE
Error when running 01_phyre_intro notebook 

### ISSUE THREAD

**Issue by Spraitazz** [facebookresearch/phyre#46]
Hi, I am getting the following error when running cell [6]:

TypeError: render(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[int]) -> List[int]
![Screenshot_2021-01-17 phyre_intro - Jupyter Notebook](https://user-images.githubusercontent.com/10031471/104837352-90b7e980-58bc-11eb-8405-800c940b39f0.png)

**Comment by akhti** [comment]
Hi there!

1. I've just tried to run this in colab and it worked. Could you try to run and see if you see the error anywhere? https://colab.research.google.com/github/facebookresearch/phyre/blob/master/examples/01_phyre_intro.ipynb
2. If colab works, what version of phyre are you using? `!pip freeze | grep phyre` in a notebook

**Comment by Spraitazz** [comment]
Hi, thanks for the quick reply.

1. The cell in question runs without error in the colab notebook you've linked.
2. The output of this is the following: -e git+https://github.com/facebookresearch/phyre.git@f6c6c973ef49239305372e9d18f664fa155bd18d#egg=phyre&subdirectory=src/python

Could this have to do with the fact that "pip install phyre" (in a conda env with python=3.6) returns

"ERROR: Could not find a version that satisfies the requirement phyre
ERROR: No matching distribution found for phyre"

and so I've had to install it through

conda env create -f env.yml
source activate phyre
pip install -e src/python

**Comment by Spraitazz** [comment]
Solved by cloning the branch "release_v22" and installing that. Thanks!
