### ISSUE TITLE
Python 3.8 Version

### ISSUE THREAD

**Issue by aks2203** [facebookresearch/phyre#47]
Hi there, I'm interested in using Phyre for a project that is in Python 3.8. I can easily pip install the package in a 3.6 env, but not a 3.8 env. Is there anything that would break in 3.8? Can the package be updated to handle this?

**Comment by akhti** [comment]
Hey! Everything should work. Could you try these instructions:
https://github.com/facebookresearch/phyre/blob/master/INSTALLATION.md#installation-from-source

But edit https://github.com/facebookresearch/phyre/blob/master/env.yml to use python 3.8?

**Comment by aks2203** [comment]
Hi, thanks for the quick reply. The build from source instructions are leading to errors like "npm not found". While I can install everything needed to build locally, pip seems to build seamlessly in a 3.6 env. For my use case, I think it's easier to move to 3.6 so I'll do that for this project. Thank you for the help!

**Comment by ZhiyuanChen** [comment]
I have successfully built a package
Can I ask how to build it for release?
`python setup.py sdist` seems not working

**Comment by akhti** [comment]
I've built wheels for python versions 3.{6,7,8,9} and also added instructions on how to build things for these versions from scratch. Hope this helps
