### ISSUE TITLE
Fails to build with missing files

### ISSUE THREAD

**Issue by ccoulombe** [facebookresearch/phyre#67]
Phyre fails to build for a few reasons.

Using the `HEAD` of the repo, or the branch `build-wheel-0.2.1`, build fails with missing files:
```
(27028) cmake_build (main) $ CONDA_PREFIX=$EBROOTTHRIFT cmake .. -DCMAKE_PREFIX_PATH=$VIRTUAL_ENV/lib/python3.8/site-packages
(27028) cmake_build (main) $ make
...
[ 63%] Building CXX object CMakeFiles/thrift_task.dir/gen-cpp/scene_constants.cpp.o
c++: error:  phyre/cmake_build/gen-cpp/scene_constants.cpp: No such file or directory
c++: fatal error: no input files
```

It seems that the files are not generated from `thrift -r --gen cpp phyre/src/if/task.thrift`

Also, the README should properly document the required dependencies and how to build from source.
e.g. Boost, Thrift and Pybind11 are required.

**Comment by akhti** [comment]
The env.yml contains all the dependencies:
https://github.com/facebookresearch/phyre/blob/main/env.yml

See docs on installation from the source here
https://github.com/facebookresearch/phyre/blob/main/INSTALLATION.md
